# lucky_num as integer to store the random number generated by the computer
import random
lucky_num = random.randint(1,10)
print(lucky_num)
guess = int(input("Try to guess the lucky number, GOOD LUCK...!!: "))
while guess != lucky_num:
    if guess > lucky_num:
        print("Too high")
        guess = int(input("Try guessing again: "))
    else:
        print("Too low")
        guess = int(input("Try guessing again: "))
if guess == lucky_num:
    print("Correct")